name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [8.4, 8.3]

    name: PHP ${{ matrix.php }} - PHPUnit

    steps:
    - uses: actions/checkout@v4
    - uses: shivammathur/setup-php@v2
      with:
        php-version: 8.4
        ini-values: error_reporting=E_ALL
        tools: composer:v2
    - name: Set Framework Version
      run: composer config version "1.0-dev"
    - name: Install Dependencies
      uses: nick-fields/retry@v3
      with:
        timeout_minutes: 5
        max_attempts: 5
        command: composer update --prefer-dist --no-interaction --no-progress
    - name: Run Tests
      run: vendor/bin/phpunit --display-deprecations --fail-on-deprecation
